### ISSUE TITLE
Distance and speed data getting lost

### ISSUE THREAD

**Issue by hankhank10** [j33433/MPowerTCX#1]
Had an issue with a file today where the distance and speed data was stripped out from the CSV file when converted over to the TCX.  It's there in the CSV but distance shows up as 0 when converted.

Have attached both input CSV and output TCX.

Running v1.1.4 on Mac.

[No distance issue.zip](https://github.com/j33433/MPowerTCX/files/817666/No.distance.issue.zip)

**Comment by hankhank10** [comment]
I am an idiot. There is a check box.

**Comment by j33433** [comment]
v1.1.6 fixes some checkbox annoyances
