### ISSUE TITLE
Mac : Error on launch

### ISSUE THREAD

**Issue by fletort** [j33433/MPowerTCX#10]
I am unable to open the application, it gives me immediatly an error:

mpowertcx Error

open COnsole or Terminate are the only proposed option

**Comment by j33433** [comment]
What OS version are you using? I suspect there are problems with newer versions of OS X that I haven't had a chance to test.

**Comment by j33433** [comment]
I finally have a Mojave machine now and was able to make a release for it. Please test and let me know either way.

**Comment by j33433** [comment]
The installer has been obsoleted and the online version https://upload.bike should work for everyone.
