### ISSUE TITLE
TheSufferfest format not up to date

### ISSUE THREAD

**Issue by MJLagerwerf** [j33433/MPowerTCX#11]
From TheSufferfest class the load method assumes the below header. 

```
      peek == ['ticks', 'time', 'power', 'cadence', 'heartRate', 'speed', 'targetPower', 'targetHeartRateZone', 'targetCadence', 
```

However, I guess due to the new Wahoo SYSTM app, the header has now changed to the following (see below). So I guess an update is in order
```
[ticks, videoTimestamp, targetPower4dpType, intervalId, timeOfDayTimestamp, distanceMeters, speedVirtualMps, distanceVirtualMeters, workoutPosition, powerMatchOffset, cadence, speed, heartRate, power, distanceSensorMeters, trainerPower, time, targetPower, targetHeartRateZone, targetCadence, targetRpe, secondsSinceStart, grade, speedSensorMps, leftPower, rightPower]
```

Additionaly, my file had NaNs in the entries, which the code could not handle as well. 

Lastly, thanks for making this app! It saved me today :D

**Comment by j33433** [comment]
Thanks. I saw the new app launch, but haven't tried it. Can you attach a workout file?

**Comment by MJLagerwerf** [comment]
There you go! 
[wahoo_systm_activity.csv](https://github.com/j33433/MPowerTCX/files/7447602/wahoo_systm_activity.csv)

**Comment by j33433** [comment]
I know it's been a while. If you are still there, can you check this output?
[wahoo.zip](https://github.com/j33433/MPowerTCX/files/8052395/wahoo.zip)

**Comment by j33433** [comment]
New version is online at https://upload.bike
